Name: PopUpsSettings
Type: FolderType
Children:
- Name: ManualModePopUp
  Id: g=1632ecf4a81aa13559c7e27cd8b14499
  Supertype: Image
  ReferenceType: HasComponent
  Children:
  - Name: Path
    Type: BaseDataVariableType
    DataType: ResourceUri
    Value: "ns=36;%PROJECTDIR%/Images/SlateBlueOpacityChangeover95.bmp"
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 690.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Button1
    Type: Button
    Children:
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 1
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 80.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 80.0
    - Name: BackgroundColor
      Type: BaseDataVariableType
      DataType: Color
      ModellingRule: Optional
    - Name: ImagePath
      Type: BaseDataVariableType
      DataType: ResourceUri
      ModellingRule: Optional
      Value: "ns=36;%PROJECTDIR%/Images/Close_White.bmp"
    - Name: ImageWidth
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 20.0
    - Name: ImageHeight
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 20.0
    - Name: MouseClickEventHandler1
      Type: EventHandler
      Children:
      - Name: ListenEventType
        Type: PropertyType
        DataType: NodeId
        Value: "/Types/EventTypes/BaseEventType/MouseEvent/MouseClickEvent"
      - Name: MethodsToCall
        Type: BaseObjectType
        Children:
        - Name: MethodContainer1
          Type: BaseObjectType
          Children:
          - Name: ns=7;ObjectPointer
            Type: NodePointer
            DataType: NodeId
            Value: "/Objects/Commands/VariableCommands"
            Children:
            - Name: Kind
              Type: PropertyType
              DataType: NodeId
              Value: "/Types/ObjectTypes/BaseObjectType"
          - Name: ns=7;Method
            Type: BaseDataVariableType
            DataType: String
            Value: "Set"
          - Name: InputArguments
            Type: BaseObjectType
            Children:
            - Name: VariableToModify
              Type: BaseDataVariableType
              DataType: VariablePointer
              Children:
              - Name: DynamicLink
                Type: DynamicLink
                DataType: NodePath
                Value: "../../../../../../../../StartSteps/ModalToggle_1@NodeId"
            - Name: Value
              Type: BaseDataVariableType
              DataType: Boolean
            - Name: ArrayIndex
              Type: BaseDataVariableType
              DataType: UInt32
              ValueRank: ScalarOrOneDimension
      - Name: EventArguments
        Type: MouseClickEvent
        Children:
        - Name: EventId
          Type: PropertyType
          DataType: ByteString
        - Name: EventType
          Type: PropertyType
          DataType: NodeId
        - Name: SourceNode
          Type: PropertyType
          DataType: NodeId
        - Name: SourceName
          Type: PropertyType
          DataType: String
        - Name: Time
          Type: PropertyType
          DataType: UtcTime
        - Name: ReceiveTime
          Type: PropertyType
          DataType: UtcTime
        - Name: Message
          Type: PropertyType
          DataType: LocalizedText
        - Name: Severity
          Type: PropertyType
          DataType: UInt16
  - Name: Label1
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":36,"TextId":"1. Put machine in Manual Mode"}
    - Name: FontSize
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 20.0
    - Name: TextColor
      Type: BaseDataVariableType
      DataType: Color
      ModellingRule: Optional
      Value: "#ffffff"
    - Name: WordWrap
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 95.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 2
    - Name: RightMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
  - Name: Label2
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":36,"TextId":"Manual Mode"}
    - Name: FontSize
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 25.0
    - Name: TextColor
      Type: BaseDataVariableType
      DataType: Color
      ModellingRule: Optional
      Value: "#ffffff"
    - Name: WordWrap
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 2
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 1
    - Name: BottomMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 327.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: RightMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: FontWeight
      Type: BaseDataVariableType
      DataType: FontWeightEnum
      ModellingRule: Optional
      Value: 600
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: -1.0
  - Name: Label3
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":36,"TextId":"1. Close all doors__2. Pull out E-stop__3. Press machine reset button"}
    - Name: FontSize
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 20.0
    - Name: TextColor
      Type: BaseDataVariableType
      DataType: Color
      ModellingRule: Optional
      Value: "#ffffff"
    - Name: WordWrap
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 220.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 2
  - Name: Label4
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"NamespaceIndex":36,"TextId":"Machine Reset Steps"}
    - Name: FontSize
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 25.0
    - Name: TextColor
      Type: BaseDataVariableType
      DataType: Color
      ModellingRule: Optional
      Value: "#ffffff"
    - Name: WordWrap
      Type: BaseDataVariableType
      DataType: Boolean
      ModellingRule: Optional
      Value: true
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 2
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 1
    - Name: BottomMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 200.0
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: RightMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: FontWeight
      Type: BaseDataVariableType
      DataType: FontWeightEnum
      ModellingRule: Optional
      Value: 600
  - Name: Visible
    Type: BaseDataVariableType
    DataType: Boolean
    Value: true
